yolo_model:

  config_file:
    name: yolov3-tiny_xnor-RAS.cfg
  weight_file:
    name: yolov3-tiny_xnor-RAS_10400.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      -Obstacle
      -Red Cube
      -Red Hollow Cube
      -Blue Cube
      -Green Cube
      -Yellow Cube
      -Yellow Ball
      -Red Ball
      -Red Cylinder
      -Green Cylinder
      -Green Hollow Cube
      -Blue Triangle
      -Purple Cross
      -Purple Star
      -Orange Cross
      -Patric 
